apiVersion: v1
data:
  API_KEY: NTc3MTc3NjY2NjQ5MTg2
  API_SECRET: b2ZQX1BRS3pJQVhvWnE4UEZhNlptWHNfWkQ4
  CLIENT_URL: IGh0dHA6Ly8xMjcuMC4wLjE6MzI5MjU=
  CLOUD_NAME: ZGJtd21vczh2
  DATABASE: bW9uZ29kYitzcnY6Ly9zdHVkZW50Y3NlMTIzNDU2Nzg5X2RiX3VzZXI6a3VyYWppQHNvY2lhbGFwcC5vdzF1cDR4Lm1vbmdvZGIubmV0L3NvY2lhbF9hcHA=
  EMAIL_PASS: eWl0YW5yaXlsa3ljenlnbQ==
  EMAIL_USER: c3R1ZGVudGNzZTEyMzQ1Njc4OUBnbWFpbC5jb20=
  JWT_SECRET: YTRmYTk3ZDMyYWEwNDg5ZWFiMjYzMGE5NTI3MGNhZDQ3OTM0Mzc3ODdlNGIxOWJkMmVmM2Y5N2E4MzNiMjYzMDMxY2IxMjlmNWM1YzUyZTEwNzA2MjM4ZDk2ZjM4NTdj
kind: Secret
metadata:
  name: nexora-backend-secrets
  namespace: nexora
